version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: hotel_booking_db
    restart: always
    environment:
      POSTGRES_USER: hotel_user
      POSTGRES_PASSWORD: alimurad05
      POSTGRES_DB: hotel_booking
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: